### ISSUE TITLE
自定义存档写入地址不正确。

### ISSUE THREAD

**Issue by hyprocritor** [huhao1987/RMMV-android-deployment#1]
minSdkVersion 26
        targetSdkVersion 30
下，自定义存档会写入/data/data/app_path/files目录下而不是sdcard目录。
代码如下：
` rpgwebview.setgamesavefolder(getExternalFilesDir("Caches").getAbsolutePath());
        rpgwebview.build();
`
结果是造成在/data/data/app_path/files会存在一个/data/data/app_path/files/storage/emulated/0/Android/data的目录……
存档还是无法被备份。

**Comment by huhao1987** [comment]
因为getExternalFilesDir返回的是软件自带目录。
sd卡目录可以用getExternalStorageDirectory()，但是如果系统大于Android 6必须动态获取写入和读取手机存储权限

**Comment by huhao1987** [comment]
> 因为getExternalFilesDir返回的是软件自带目录。
> sd卡目录可以用getExternalStorageDirectory()，但是如果系统大于Android 6必须动态获取写入和读取手机存储权限

因为getExternalFilesDir返回的是软件自带目录。
sd卡目录可以用getExternalStorageDirectory()，但是如果系统大于Android 6必须动态获取写入和读取手机存储权限

**Comment by huhao1987** [comment]
>         minSdkVersion 26
>         targetSdkVersion 30
> 下，自定义存档会写入/data/data/app_path/files目录下而不是sdcard目录。
> 代码如下：
> ` rpgwebview.setgamesavefolder(getExternalFilesDir("Caches").getAbsolutePath());
>         rpgwebview.build();
> `
> 结果是造成在/data/data/app_path/files会存在一个/data/data/app_path/files/storage/emulated/0/Android/data的目录……
> 存档还是无法被备份。

因为getExternalFilesDir返回的是软件自带目录。
sd卡目录可以用getExternalStorageDirectory()，但是如果系统大于Android 6必须动态获取写入和读取手机存储权限

**Comment by hyprocritor** [comment]
这个问题我重新确认一下，与getexternalfilesdir还是externalstoragedirectory无关，这个是Android 10开始有的新特性，scoped storage的问题。大于29的SDK会强制写到app的internal部分里。如果要写到外部，需要一些额外的写法。
我看看把SDK降低到26能不能解决。

**Comment by huhao1987** [comment]
> 这个问题我重新确认一下，与getexternalfilesdir还是externalstoragedirectory无关，这个是Android 10开始有的新特性，scoped storage的问题。大于29的SDK会强制写到app的internal部分里。如果要写到外部，需要一些额外的写法。
> 我看看把SDK降低到26能不能解决。

哦，如果是读写权限问题，把targetsk降到29，在application里加requestLegacyExternalStorage=“true”
应该就可以了

**Comment by hyprocritor** [comment]
改了以后没啥效果，不知道啥原因。
clone这个repo到本地以后，
目前只找到一种方法来写到外部，就是利用mcontext.externalcachedir来获取外部存储。只有那个File才是正确的指向外部存储的，只用File(path）创建的统统指向了scoped storage。不知道是不是设备问题(三星S10+, ANDROID 10).

原因懒得找了，姑且能用不是……
