### ISSUE TITLE
Slow loading of the save menu and how many saved games there are.

### ISSUE THREAD

**Issue by HimikoS** [huhao1987/RMMV-android-deployment#2]
Hello, it works well, and very good work only that when I use the plugins to change the save location of games, I play it as long as it does not exceed 3 or 4 saves, it loads me well, but if I save more than 4 when I enter the device game loading takes time to show how many saved games there are.

**Comment by huhao1987** [comment]
Hi, the plugin only uses js-android port to do two things: 
1.Store the saved data into file in the device.
2.Load the sav files from device. 
The android code do nothing to process the data.  So all the data will still be processed by js from RMMV.
As I know, RMMV will save a lot of data inside the save. So save files will become bigger and bigger as long as you play the game. I didn`t check the detail from RMMV, and not sure if RMMV will load all files together, but if these save files are huge to load, it might take time to load them.

**Comment by HimikoS** [comment]
Well after so much searching I found a plugin that speeds up the loading and saving menu (KMS_AccelerateFileScene). now if the games are loaded and saved quickly, also thanks for the help. Well I close this topic.
