### ISSUE TITLE
作者大佬，我想问一下使用的问题

### ISSUE THREAD

**Issue by NPC2000** [huhao1987/RMMV-android-deployment#3]
作者大佬，不好意思，打扰到你了，我想问一下这个应该怎么使用，我使用的是MV Android Client这个项目，但是我通过你发的使用步骤走到5.3这个步骤就不知道怎么操作了，而且我发现打开MV Android Clients项目，项目目录结构中没有主activity和layout文件。也没看见MainActivity这个文件，只是在MV Android Clients的WebPlayerActivity找到了oncreate方法，但是我添加了
`rpgPlayerView rpgwebview=findViewById(R.id.rpgwebview)`
`rpgwebview.build()`
`rpgwebview.Playgame("//android_asset/www/index.html")`
显示无法解析rpgPlayerView , Playgame。
然后我在poject1看见了你说需要引用库，我就把你发行版的1.0.8下载之后直接File->New->import modules，但是直接报错。

**Comment by huhao1987** [comment]
我教程里写的应该是直接用Android studio新建一个新项目，mv那个老项目版本太老，现在新版的Android studio根本识别不了了

**Comment by NPC2000** [comment]
> 我教程里写的应该是直接用Android studio新建一个新项目，mv那个老项目版本太老，现在新版的Android studio根本识别不了了

好的，谢谢大佬的解答。所以我应该用Android studio创建一个新项目，之后File->New->import modules导入库，再进行基础步骤吗？

**Comment by huhao1987** [comment]
> > 我教程里写的应该是直接用Android studio新建一个新项目，mv那个老项目版本太老，现在新版的Android studio根本识别不了了
> 
> 好的，谢谢大佬的解答。所以我应该用Android studio创建一个新项目，之后File->New->import modules导入库，再进行基础步骤吗？

可以从步骤3开始跟着步骤添加远程仓库，不用导入module

**Comment by NPC2000** [comment]
> > > 我教程里写的应该是直接用Android studio新建一个新项目，mv那个老项目版本太老，现在新版的Android studio根本识别不了了
> > 
> > 
> > 好的，谢谢大佬的解答。所以我应该用Android studio创建一个新项目，之后File->New->import modules导入库，再进行基础步骤吗？
> 
> 可以从步骤3开始跟着步骤添加远程仓库，不用导入module

谢谢大佬，我终于导入成功了，原因是Gradle版本是7.3， maven { url 'https://jitpack.io' }这个得添加到settings.gradle里面。虽然已经成功了，但是我app里面的项目里面还是没有MainActivity和layout文件，不管我怎么刷新gardle依赖项和重新加载gardle项目，我的目录还是没有什么变化。所以我想问一下，这个MainAcitivty和layout文件是需要自己手动创建吗？

**Comment by huhao1987** [comment]
> 
你新建项目的时候可以选择“empty activity”,这个会给你创建一个默认的Activity

**Comment by NPC2000** [comment]
> > 
> 
> 你新建项目的时候可以选择“empty activity”，这个会给你创建一个默认的Activity

谢谢大佬，我再去试一下

**Comment by NPC2000** [comment]
> > 
> 
> 你新建项目的时候可以选择“empty activity”,这个会给你创建一个默认的Activity

大佬，不好意思，我又打扰你了，我跟着步骤创建了Assets，并把www文件夹复制进去，也在MainActivity的oncreate方法中加入java的代码，但是rpgwebview.Playgame("//android_asset/www/index.html")这行代码报错，显示'hh.rpgmakerplayer.webviewmodule.rpgPlayerView' 中的 'Playgame(java.lang.String, boolean)' 无法应用于 '(java.lang.String)'

**Comment by huhao1987** [comment]
截图看看吧，没看到代码我也很难定位是什么错误

**Comment by NPC2000** [comment]
![1](https://user-images.githubusercontent.com/113622959/192232377-bab7c4d4-cb31-4c6e-a3be-cb06c62d6e87.png)
大佬，不好意思，久等了

**Comment by huhao1987** [comment]
哦，你这里用的java，所有后面有个参数不能直接忽略，你改成rpgwebview.Playgame("//android_asset/www/index.html",false)应该就行了

**Comment by NPC2000** [comment]
> 哦，你这里用的java，所有后面有个参数不能直接忽略，你改成rpgwebview.Playgame("//android_asset/www/index.html",false)应该就行了

大佬，谢谢你，我已经成功了，非常感谢你的帮助
